tool: exomiser
tool_version: 14.0.1
# NOTE gene-only preset analysis should only be run with Exomiser versions >= 13.2.0
variant_analysis: False
gene_analysis: False
disease_analysis: True
tool_specific_configuration_options:
  environment: local
  exomiser_software_directory: exomiser-cli-14.0.1
  analysis_configuration_file: None
  max_jobs: 0
  application_properties:
    remm_version:
    cadd_version:
    hg19_data_version: 2406
    hg19_local_frequency_path:
    hg38_data_version:
    hg38_local_frequency_path:
    phenotype_data_version: 2406
    # either none, simple, or caffeine
    cache_type: none
    cache_caffeine_spec:
  post_process:
    # For Exomiser, valid ranking methods include combinedScore, priorityScore, variantScore or pValue
    score_name: combinedScore
    # sort order should be specified to either ASCENDING or DESCENDING
    # ASCENDING orders results with the lowest values ranked first
    # DESCENDING orders results with the highest values ranked first
    # NOTE when changing the score_name ensure the sort_order is also correct
    sort_order: DESCENDING
